title: pinebery
description: >
  Pine-ber-EE | tjcsc | forensics, crypto, OSINT write-ups.
url: https://pinebery.github.io
baseurl: "/ctf"
markdown: kramdown
kramdown:
  input: GFM

author:
  name: "Pine-ber-EE"
  email: ""

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "write-ups"
    values:
      layout: "post"
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
