title: snowbird91
description: >
  Andrew (snowbird91) | 0xf1sh & tjcsc | forensics, crypto, OSINT write-ups.
url: https://snowbird91.github.io
baseurl: "/ctf"
markdown: kramdown

author:
  name: "snowbird91 (Andrew)"
  email: ""

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "write-ups"
    values:
      layout: "post"
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
