title: snowbird91
description: >
  Andrew (snowbird91) | 0xf1sh & tjcsc | forensics, crypto, OSINT write-ups.
url: https://snowbird91.github.io
baseurl: "/ctf"
markdown: kramdown

# for atom feed
author:
  name: "snowbird91 (Andrew)"
  email: ""

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "all_collections/_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
